# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: pipra_left@1//zmk
    artifact-name: pipra_left_1_0_0
  - board: pipra_left@1//zmk
    snippet: enable_ec_calibrator
    artifact-name: pipra_left_1_0_0_calibrator
  - board: pipra_right@1//zmk
    artifact-name: pipra_right_1_0_0
  - board: pipra_right@1//zmk
    snippet: enable_ec_calibrator
    artifact-name: pipra_right_1_0_0_calibrator
  - board: pipra_right@0.1//zmk
    artifact-name: pipra_right_0_1_0
  - board: pipra_right@0.1//zmk
    snippet: enable_ec_calibrator
    artifact-name: pipra_right_0_1_0_calibrator
